# Generated by Django 5.1.4 on 2024-12-23 19:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("employee_list", "Can list all employees"),
                                ("employee_update", "Can update all employees"),
                                ("employee_create", "Can create employees"),
                                ("employee_destroy", "Can delete employees"),
                                (
                                    "salary_view_all",
                                    "Can view salaries of all employees",
                                ),
                                ("salary_update", "Can update salaries"),
                                ("salary_delete", "Can delete salaries"),
                                ("leave_view_all", "Can view all leave requests"),
                                ("leave_update_status", "Can update leave status"),
                                ("leave_delete", "Can delete leave records"),
                                ("department_create", "Can create departments"),
                                ("department_view_all", "Can view all departments"),
                                ("department_delete", "Can delete departments"),
                                ("department_update", "Can update departments"),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        help_text="List of permissions assigned to this role",
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("manager", models.BooleanField(blank=True, default=False, null=True)),
                ("hire_date", models.DateField()),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Each employee must belong to one department",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="departments.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("leave_type", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("pay_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pay_period", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
