# Generated by Django 5.1.4 on 2024-12-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
